#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': '',
 'author_email': '',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': '',
 'download_url': '',
 'entry_points': '[openmdao.component]\ncfxwrapper.cfxwrapper.CFXWrapper=cfxwrapper.cfxwrapper:CFXWrapper\ncfxwrapper.cfxwrappergenerator.TestCFX=cfxwrapper.cfxwrappergenerator:TestCFX\n\n[openmdao.container]\ncfxwrapper.cfxwrapper.CFXWrapper=cfxwrapper.cfxwrapper:CFXWrapper\ncfxwrapper.cfxwrappergenerator.TestCFX=cfxwrapper.cfxwrappergenerator:TestCFX',
 'include_package_data': True,
 'install_requires': ['openmdao.main'],
 'keywords': ['openmdao'],
 'license': '',
 'maintainer': '',
 'maintainer_email': '',
 'name': 'cfxwrapper',
 'package_data': {'cfxwrapper': []},
 'package_dir': {'': 'src'},
 'packages': ['cfxwrapper'],
 'url': '',
 'version': '0.1.0',
 'zip_safe': False}


setup(**kwargs)

